version: '3.7'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./default-user.xml:/etc/clickhouse-server/users.d/default-user.xml

volumes:
  clickhouse-data: